jobs:
    build:
        name: Hellow world action
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./action-a
              env:
                  MY_NAME: "Alice"
